Repository openshift/cluster-authentication-operator, pull requests merged in 2019-10, with the labels that each got.

#202 Add examples for LDAP IdP and RequestHeader IdP
  examples/oauth/ldap/ldapconfig.yaml
  examples/oauth/request_header/config_requestheader.sh
  examples/oauth/request_header/custom.cnf
  examples/oauth/request_header/request_token.sh
  examples/oauth/request_header/requestheaderidp.yaml
Labels: approved, lgtm, size/L

#205 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#204 update README and Makefile
  Makefile
  README.md
Labels: approved, lgtm, size/S
