Repository openshift/cluster-authentication-operator, pull requests merged in 2019-08, with the labels that each got.

#151 Bug 1729289: Fix bug where favicon is incorrect (was Shadowman, now OpenShift)
  manifests/06_branding_secret.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#171 Watch Proxy status instead of spec
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/XS

#173 Bug 1740121: Prevent global sync error degraded status flapping
  pkg/operator2/operator.go
  pkg/operator2/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#162 Bug 1733978: Correct race between config sync loop and resource syncer [4.1]
  Makefile
  pkg/operator2/branding.go
  pkg/operator2/configsync.go
  pkg/operator2/configsync_test.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/resourceversion.go
  pkg/operator2/resourceversion_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#179 Bug 1740363: Use specific reasons for all route degraded errors
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#181 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#172 Inject payload's system store with proxy CA when specified
  manifests/03_configmap.yaml
  manifests/07_deployment.yaml
  pkg/operator2/deployment.go
  pkg/operator2/idp.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#184 Bug 1740366: Add strict validation for router certs
  pkg/operator2/route.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#176 Bug 1707905: Update route when ingress domain changes
  pkg/operator2/route.go
  pkg/operator2/route_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#188 Log inputs to operator.openshift.io/rvs-hash
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
  pkg/operator2/resourceversion.go
  pkg/operator2/resourceversion_test.go
Labels: approved, lgtm, size/M

#189 Bug 1747480: Make SNI output stable when multiple ingress domains are configured
  pkg/operator2/route.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#190 Explicitly mark trusted-ca-bundle optional for OAuth server
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M
