Repository openshift/cluster-authentication-operator, pull requests merged in 2019-01, with the labels that each got.

#10 Update image references to use cluster-authentication-operator
  manifests/0000_09_cluster-osin-operator_05_deploy.yaml
  manifests/image-references
Labels: approved, lgtm, size/XS

#13 validate session secrets
  pkg/operator2/operator.go
  pkg/operator2/secret.go
  pkg/operator2/secret_test.go
Labels: approved, lgtm, size/L

#15 Bump api and client-go
  pkg/operator2/auth.go
  pkg/operator2/oauth.go
  vendor/github.com/openshift/api/.gitattributes
  vendor/github.com/openshift/api/apps/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-swagger-docs.sh
  vendor/github.com/openshift/api/hack/verify-swagger-docs.sh
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/quota/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/tools/genswaggertypedocs/swagger_type_docs.go
  vendor/github.com/openshift/api/user/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/webconsole/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/identityprovider.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/glide.lock
Labels: approved, lgtm, size/XXL

#18 Honor route name assigned to our service in our config
  pkg/operator2/configmap.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
Labels: approved, lgtm, size/M

#21 Fix service and container port
  pkg/operator2/deployment.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/service.go
Labels: approved, lgtm, size/S

#22 Fix informers to correctly watch secrets and configmaps
  pkg/operator2/configsync.go
  pkg/operator2/helpers.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#25 Ensure default custom resources exist for top level config
  pkg/operator2/starter.go
Labels: approved, lgtm, size/M

#24 Get secret/configmaps information from config for all IdPs
  pkg/operator2/configsync.go
Labels: approved, lgtm, size/L

#29 New build?
  README.md
Labels: approved, lgtm, size/XS

#38 CI test
  README.md
Labels: approved, lgtm, size/XS

#41 No run level
  manifests/cluster-authentication-operator_00_roles.yaml
  manifests/cluster-authentication-operator_01_namespace.yaml
  manifests/cluster-authentication-operator_02_crd.yaml
  manifests/cluster-authentication-operator_03_cm.yaml
  manifests/cluster-authentication-operator_04_sa.yaml
  manifests/cluster-authentication-operator_05_deploy.yaml
  manifests/cluster-authentication-operator_06_authentication_crd.yaml
  manifests/cluster-authentication-operator_07_oauth_crd.yaml
Labels: approved, lgtm, size/XS

#44 Kick CI
  README.md
Labels: approved, lgtm, size/XS

#52 Kick CI
  README.md
Labels: approved, lgtm, size/XS

#53 Prevent deadlock on console config
  pkg/operator2/operator.go
Labels: approved, lgtm, size/XS

#54 Support optional resources
  pkg/operator2/configsync.go
  pkg/operator2/deployment.go
  pkg/operator2/helpers.go
  pkg/operator2/idp.go
  pkg/operator2/oauth.go
Labels: approved, lgtm, size/L

#48 handle kubeapiserver api movement
  pkg/operator/operator.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M
