Repository openshift/cluster-authentication-operator, pull requests merged in 2019-05, with the labels that each got.

#124 Bug 1700891: OCP Branding
  Dockerfile
  Dockerfile.rhel7
  manifests/06_branding_secret.yaml
  manifests/07_deployment.yaml
  manifests/08_clusteroperator.yaml
  pkg/operator2/brand_ocp.go
  pkg/operator2/brand_okd.go
  pkg/operator2/branding.go
  pkg/operator2/consoleconfig.go
  pkg/operator2/deployment.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/L

#125 Preserve last transition time on status condition updates
  manifests/06_branding_secret.yaml
  pkg/operator2/operator.go
Labels: approved, lgtm, size/S

#126 Bug 1706894: Make oauth-openshift.<ingress_domain> the permanent issuer of the OAuth server
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
  manifests/04_roles.yaml
  manifests/05_serviceaccount.yaml
  manifests/08_clusteroperator.yaml
  pkg/operator2/ingress.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
Labels: approved, size/L

#127 Bug 1707049: Use TerminationMessageFallbackToLogsOnError for OAuth server
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/S

#128 Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down
  manifests/07_deployment.yaml
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/M
