Repository openshift/cluster-authentication-operator, pull requests merged in 2019-04, with the labels that each got.

#103 Bug 1695244: Correctly determine operand version
  manifests/cluster-authentication-operator_03_version-mapping.yaml
  manifests/cluster-authentication-operator_05_deploy.yaml
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#104 Fix config informer to not use WithTweakListOptions
  pkg/operator2/starter.go
Labels: approved, lgtm, size/XS

#105 Bug 1694173: Improve status reporting
  pkg/operator2/operator.go
  pkg/operator2/status.go
Labels: approved, lgtm, size/M

#92 feat(manifests): configure cluster-montoring on auth resources
  manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
  manifests/00_namespace.yaml
  manifests/01_config.crd.yaml
  manifests/02_service.yaml
  manifests/03_configmap.yaml
  manifests/04_roles.yaml
  manifests/05_serviceaccount.yaml
  manifests/06_deployment.yaml
  manifests/07_clusteroperator.yaml
Labels: approved, lgtm, size/L

#106 Make it easier to control operand image pull policy
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/S

#108 Handle defaulting of top level config
  pkg/operator2/auth.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/M

#107 Check osin deployment availability after other checks
  pkg/operator2/deployment.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/status.go
Labels: approved, lgtm, size/L

#111 bug 1700903: standardize resource names
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
  manifests/02_service.yaml
  manifests/03_configmap.yaml
  manifests/04_roles.yaml
  manifests/05_serviceaccount.yaml
  manifests/06_deployment.yaml
  pkg/operator2/ca.go
  pkg/operator2/configsync.go
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/secret.go
  pkg/operator2/starter.go
  pkg/version/version.go
Labels: approved, lgtm, size/L

#113 README: add steps for simple test IdP config
  README.md
Labels: approved, lgtm, size/M

#116 Default mapping method to claim
  README.md
  pkg/operator2/oauth.go
Labels: approved, lgtm, size/XS

#112 Use CVO for management of operator config resource
  manifests/02_config.cr.yaml
  pkg/operator2/starter.go
Labels: approved, lgtm, size/M

#114 Bug 1694818: remove emoji from event logs
  pkg/boilerplate/operator/option.go
Labels: approved, lgtm, size/S

#117 Add node-selector annotation to namespace
  manifests/00_namespace.yaml
Labels: lgtm, size/XS

#118 Bug 1694878: Confirm that all KAS have observed our OAuth metadata
  pkg/operator2/idp.go
  pkg/operator2/operator.go
  pkg/operator2/transport.go
Labels: approved, lgtm, size/L

#120 Bug 1692290: Sort RVs before hashing them
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/XS

#122 Bug 1703504: Get route host from status
  pkg/operator2/route.go
Labels: approved, lgtm, size/M

#123 Bug 1703502: Enable Auth for metrics endpoint
  manifests/03_configmap.yaml
Labels: approved, lgtm, size/XS
