Repository openshift/cluster-authentication-operator, pull requests merged in 2019-02, with the labels that each got.

#57 console and kube api server operator informers: skip cache sync
  pkg/boilerplate/controller/controller.go
  pkg/boilerplate/controller/die.go
  pkg/boilerplate/controller/informer.go
  pkg/boilerplate/controller/option.go
  pkg/boilerplate/operator/option.go
  pkg/operator/operator.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/L

#60 Add CORS support for console public hostname
  pkg/operator2/console.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#63 Remove CORS for the console
  pkg/operator2/console.go
Labels: approved, lgtm, size/XS

#62 Remove top level config CRDs
  manifests/cluster-authentication-operator_06_authentication_crd.yaml
  manifests/cluster-authentication-operator_07_oauth_crd.yaml
Labels: approved, lgtm, size/M

#69 Run single replica of authentication operator
  manifests/cluster-authentication-operator_05_deploy.yaml
Labels: approved, lgtm, size/XS

#66 Redeploy when a secret/configmap from top-level config changes
  pkg/operator2/configsync.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#68 idp: fix LDAP identity provider
  pkg/operator2/idp.go
Labels: approved, lgtm, size/XS

#71 idp: add missing Teams attribute in GH IdP
  pkg/operator2/idp.go
Labels: approved, lgtm, size/XS

#64 Sync template secrets
  pkg/operator2/configsync.go
  pkg/operator2/deployment.go
  pkg/operator2/idp.go
  pkg/operator2/oauth.go
Labels: approved, lgtm, size/L

#70 chore(pkg/operator2/deployment): schedule on master nodes
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/M

#72 operator: change source of apiURL to infrastructure.config.openshift.io
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/types.go
Labels: approved, lgtm, size/L

#59 Delete operator 1
  cmd/authentication-operator/main.go
  manifests/cluster-authentication-operator_05_deploy.yaml
  pkg/cmd/operator/cmd.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/L

#76 Reduce log spam and turn off unneeded delegation
  manifests/cluster-authentication-operator_03_cm.yaml
  manifests/cluster-authentication-operator_05_deploy.yaml
Labels: approved, lgtm, size/XS

#81 Restore run level 9
  manifests/0000_09_cluster-authentication-operator_00_roles.yaml
  manifests/0000_09_cluster-authentication-operator_01_namespace.yaml
  manifests/0000_09_cluster-authentication-operator_02_config.crd.yaml
  manifests/0000_09_cluster-authentication-operator_03_cm.yaml
  manifests/0000_09_cluster-authentication-operator_04_sa.yaml
  manifests/0000_09_cluster-authentication-operator_05_deploy.yaml
  manifests/cluster-authentication-operator_01_namespace.yaml
Labels: approved, lgtm, size/M

#36 Add status updates
  pkg/operator2/operator.go
  pkg/operator2/operatorclient.go
  pkg/operator2/starter.go
  pkg/operator2/status.go
Labels: approved, lgtm, size/L

#75 Add redeploy on serving cert and operator pod template change
  pkg/operator2/ca.go
  pkg/operator2/configmap.go
  pkg/operator2/operator.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/M

#84 Create the service before waiting for serving certs
  pkg/operator2/operator.go
Labels: approved, lgtm, size/S

#85 fix template synced secret names
  pkg/operator2/configsync.go
Labels: approved, lgtm, size/XS

#79 Move to OsinServerConfig
  pkg/operator2/console.go
  pkg/operator2/infrastructure.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M
