Repository openshift/cluster-authentication-operator, pull requests merged in 2019-03, with the labels that each got.

#83 Move to a passthrough route to support mTLS
  pkg/operator2/deployment.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/M

#89 Fix status updates, move back to default runlevel
  manifests/0000_09_cluster-authentication-operator_01_namespace.yaml
  manifests/cluster-authentication-operator_00_roles.yaml
  manifests/cluster-authentication-operator_01_namespace.yaml
  manifests/cluster-authentication-operator_02_config.crd.yaml
  manifests/cluster-authentication-operator_03_cm.yaml
  manifests/cluster-authentication-operator_04_sa.yaml
  manifests/cluster-authentication-operator_05_deploy.yaml
  pkg/operator2/operatorclient.go
Labels: approved, lgtm, size/S

#87 bump(*)
  glide.lock
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/assets/template.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling_test.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_networking_test.go
  vendor/github.com/openshift/library-go/pkg/operator/render/options/manifest.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/golang.org/x/tools/cmd/golsp/main.go
  vendor/golang.org/x/tools/cmd/guru/what.go
  vendor/golang.org/x/tools/go/gcexportdata/example_test.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/internal/lsp/cache/view.go
  vendor/golang.org/x/tools/internal/lsp/cmd/definition.go
  vendor/golang.org/x/tools/internal/lsp/cmd/location.go
  vendor/golang.org/x/tools/internal/lsp/diagnostics.go
  vendor/golang.org/x/tools/internal/lsp/lsp_test.go
  vendor/golang.org/x/tools/internal/lsp/protocol/text.go
  vendor/golang.org/x/tools/internal/lsp/server.go
  vendor/golang.org/x/tools/internal/lsp/source/analysis.go
  vendor/golang.org/x/tools/internal/lsp/source/diagnostics.go
Labels: approved, lgtm, size/XXL

#90 Update operator and operand manifests for priority and imagePolicy
  manifests/cluster-authentication-operator_05_deploy.yaml
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/XS

#88 fix(operator2/deployment): run 2 replicas for redundancy
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/S

#91 Correctly handle OAuth templates
  pkg/operator2/configsync.go
  pkg/operator2/idp.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/L

#94 Add version to (cluster)operator status
  manifests/cluster-authentication-operator_05_deploy.yaml
  manifests/cluster-authentication-operator_06_clusteroperator.yaml
  pkg/operator2/operator.go
  pkg/operator2/starter.go
  pkg/operator2/status.go
Labels: approved, lgtm, size/L

#77 Improve status handling
  manifests/cluster-authentication-operator_03_version-mapping.yaml
  manifests/cluster-authentication-operator_05_deploy.yaml
  manifests/cluster-authentication-operator_06_clusteroperator.yaml
  pkg/operator2/auth.go
  pkg/operator2/configmap.go
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
  pkg/operator2/starter.go
  pkg/operator2/status.go
Labels: approved, lgtm, size/L

#80 Bug 1677587: Add openAPIV3Schema validation to operator config
  manifests/cluster-authentication-operator_02_config.crd.yaml
Labels: approved, lgtm, size/L

#98 redeploy on operatorConfig.spec changes
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
Labels: approved, lgtm, size/S

#101 Improve error messages
  pkg/operator2/ca.go
  pkg/operator2/configsync.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/secret.go
Labels: approved, lgtm, size/M

#99 Tighten APIs
  pkg/operator2/idp.go
  pkg/operator2/oauth.go
  pkg/operator2/transport.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
Labels: approved, lgtm, size/L

#102 Bug 1691488: Fix route healthz to tolerate custom wildcard certs
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/L
