Repository openshift/cluster-authentication-operator, pull requests merged in 2019-09, with the labels that each got.

#185 report degraded status if router certs are invalid
  pkg/operator2/route.go
  pkg/operator2/route_test.go
  pkg/operator2/routercerts/controller.go
  pkg/operator2/routercerts/controller_test.go
  pkg/operator2/starter.go
  test/e2e/certs_test.go
  test/library/cluster_operator.go
  test/library/crypto.go
Labels: approved, lgtm, size/XXL

#192 Bug 1751147: operator: fix typo to get injected with proxy env vars
  manifests/07_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#196 Inline constants so David does not die
  pkg/operator2/operator.go
Labels: approved, lgtm, size/M

#197 Inline all consts
  pkg/operator2/apiserver.go
  pkg/operator2/auth.go
  pkg/operator2/branding.go
  pkg/operator2/ca.go
  pkg/operator2/configmap.go
  pkg/operator2/configsync.go
  pkg/operator2/configsync_test.go
  pkg/operator2/console.go
  pkg/operator2/deployment.go
  pkg/operator2/idp.go
  pkg/operator2/infrastructure.go
  pkg/operator2/ingress.go
  pkg/operator2/oauth.go
  pkg/operator2/oauthclients.go
  pkg/operator2/operator.go
  pkg/operator2/operatorclient.go
  pkg/operator2/proxy.go
  pkg/operator2/resourceversion.go
  pkg/operator2/resourceversion_test.go
  pkg/operator2/route.go
  pkg/operator2/route_test.go
  pkg/operator2/secret.go
  pkg/operator2/secret_test.go
  pkg/operator2/service.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/XL

#198 manifests: split configmaps
  manifests/03_configmap.yaml
  manifests/03_operand_trusted_ca.yaml
  manifests/03_operator_trusted_ca.yaml
Labels: approved, lgtm, size/M

#200 Bug 1753886: Don't stomp on our own route
  pkg/operator2/route.go
  pkg/operator2/route_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
