Repository openshift/cluster-authentication-operator, pull requests merged in 2019-07, with the labels that each got.

#140 Migrate from hypershift to oauth-server image
  manifests/07_deployment.yaml
  manifests/image-references
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/S

#142 Bug 1725935: Split handling of degraded across multiple conditions
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#147 Honor CORS set via APIServer config
  glide.lock
  pkg/operator2/apiserver.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/golang.org/x/tools/cmd/present/static/notes.js
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/lsp/lsp_test.go
  vendor/golang.org/x/tools/internal/lsp/source/rename.go
  vendor/golang.org/x/tools/internal/lsp/source/signature_help.go
  vendor/golang.org/x/tools/internal/lsp/source/source_test.go
  vendor/golang.org/x/tools/internal/lsp/testdata/rename/a/random.go.golden
  vendor/golang.org/x/tools/internal/lsp/testdata/rename/a/random.go.in
  vendor/golang.org/x/tools/internal/lsp/testdata/signature/signature.go
  vendor/golang.org/x/tools/internal/lsp/tests/tests.go
Labels: approved, lgtm, size/XL

#146 Make it clear that we do not support the removed state
  pkg/operator2/operator.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/XS

#156 Introduce gosec for security checks
  Makefile
  hack/lib/util/find.sh
  hack/test-sec.sh
  tools/import-verifier/import-verifier.go
Labels: approved, lgtm, size/S

#160 Bug 1733336: Correct race between config sync loop and resource syncer
  Makefile
  pkg/operator2/branding.go
  pkg/operator2/configsync.go
  pkg/operator2/configsync_test.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/resourceversion.go
  pkg/operator2/resourceversion_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#155 deployment: add env vars from the Proxy object
  pkg/operator2/deployment.go
  pkg/operator2/operator.go
  pkg/operator2/proxy.go
Labels: approved, lgtm, size/M

#166 ask for proxy env vars to be injected for OIDC communication
  manifests/07_deployment.yaml
Labels: approved, lgtm, size/XS
