Repository openshift/cluster-authentication-operator, pull requests merged in 2020-03, with the labels that each got.

#253 Bug 1809193: Resync auth operator informer every 30 sec to tighten sync loop for .well-known check
  pkg/operator2/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#252 The oauth server should wait until it is out of rotation to shut down
  bindata/oauth-openshift/deployment.yaml
  pkg/operator2/assets/bindata.go
Labels: approved, lgtm, size/S

#258 Bug 1794311: Set namespace for route from related objects
  pkg/operator2/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#262 Bug 1794311: Set namespace for service from related objects
  pkg/operator2/starter.go
Labels: approved, bugzilla/valid-bug, lgtm

#264 scaffolding for encryption e2e tests
  Makefile
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm
