Repository openshift/cluster-authentication-operator, pull requests merged in 2020-10, with the labels that each got.

#353 Bug 1883769: Add validation for logLevel
  go.mod
  go.sum
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#354 Bug 1883792: move to klog/v2 and bump kube/openshift deps
  go.mod
  go.sum
  pkg/controllers/common/config.go
  pkg/controllers/common/route.go
  pkg/controllers/configobservation/oauth/idp_conversions.go
  pkg/controllers/configobservation/oauth/observe_idps.go
  pkg/controllers/configobservation/oauth/observe_tokenconfig.go
  pkg/controllers/deployment/default_deployment.go
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/payload/payload_config_controller.go
  pkg/controllers/readiness/unsupported_override.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/controllers/routercerts/controller.go
  pkg/operator/apiservices/sync_apiservices_oauth_apiserver.go
  pkg/operator/apiservices/sync_take_over_apiservices_oauth_apiserver.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#356 flowschema for oauth server and its operator
  manifests/09_flowschema.yaml
Labels: approved, lgtm

#348 ingressnodesavailable: fix typo in message
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
Labels: approved, lgtm

#357 remove unused vbom.ml/util dependency
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#359 BUG 1886449: p&f: assign oauth server traffic to workload-high
  manifests/09_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#358 pkg/controllers: Use library-go's IngressURI helper
  go.mod
  go.sum
  pkg/controllers/common/route.go
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/metadata/metadata_controller.go
  test/library/waits.go
  vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
  vendor/modules.txt
Labels: approved, lgtm

#362 bug 1888028: bump library-go to stop waiting on kube-apiserver availability
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#363 BUG 1888311: p&f: make oauth SAR/TokenReview traffic exempt
  manifests/09_flowschema.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#361 Bug 1887428: add ServiceMonitor for the oauth apiserver
  manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#365 Bug 1891758: deployment: update event spam
  pkg/controllers/deployment/deployment_controller.go
Labels: approved, lgtm
