Repository openshift/cluster-authentication-operator, pull requests merged in 2020-11, with the labels that each got.

#369 add current profile annotations to CVO manifests
  manifests/09_flowschema.yaml
Labels: approved, lgtm

#370 bug 1893386: update ingress node available to handle custom placement
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#366 Restrict log permissions
  bindata/oauth-apiserver/deploy.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Labels: approved, lgtm

#371 [4.6] Bug 1893803: update ingress node available to handle custom placement
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#373 Bug 1893386: Fix wrong operator config informer
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, priority/critical-urgent

#372 picks up setting `TCP_USER_TIMEOUT` socket option
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/modules.txt
Labels: approved, lgtm

#355 Add a controller to report misconfigured proxy
  go.mod
  pkg/controllers/proxyconfig/proxyconfig_controller.go
  pkg/controllers/proxyconfig/proxyconfig_controller_test.go
  pkg/operator/starter.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
Labels: approved, lgtm

#319 oauthserver: grab unsupported overrides from a prefixed tree
  pkg/controllers/payload/payload_config_controller.go
Labels: approved, lgtm

#378 Add IBM Cloud managed annotations to CVO manifests
  manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
  manifests/00_namespace.yaml
  manifests/02_config.cr.yaml
  manifests/02_service.yaml
  manifests/03_configmap.yaml
  manifests/03_openshift_service_ca.yaml
  manifests/03_operator_trusted_ca.yaml
  manifests/04_roles.yaml
  manifests/05_serviceaccount.yaml
  manifests/09_flowschema.yaml
Labels: approved, lgtm

#382 pkg/controllers/common: Fix "successfull" -> "successful" typos
  pkg/controllers/common/route.go
Labels: approved, lgtm

#381 add RBAC for the new useroauthaccesstokens
  bindata/oauth-apiserver/RBAC/useroauthaccesstokens_binding.yaml
  bindata/oauth-apiserver/RBAC/useroauthaccesstokens_clusterrole.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/starter.go
Labels: approved, lgtm

#380 always claim control over oauth and user APIs
  pkg/operator/apiservices/sync_apiservices_oauth_apiserver.go
  pkg/operator/apiservices/sync_apiservices_oauth_apiserver_test.go
  pkg/operator/apiservices/sync_take_over_apiservices_oauth_apiserver.go
  pkg/operator/apiservices/sync_take_over_apiservices_oauth_apiserver_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_cloudcredential.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_clustercsidriver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_config.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_etcd.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_ingresscontroller.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubescheduler.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubestorageversionmigrator.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_serviceca.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogapiserver.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_storage.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_imagecontentsourcepolicy.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  vendor/modules.txt
Labels: approved, lgtm
