Repository openshift/cluster-authentication-operator, pull requests merged in 2020-04, with the labels that each got.

#265 Pick up PatternFly bug fix [1], update logos, fix favicon
  manifests/06_branding_secret.yaml
Labels: approved, lgtm

#242 Add only a basic config observer
  go.mod
  go.sum
  pkg/operator2/apiserver.go
  pkg/operator2/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator2/configobservation/console/observe_consoleurl.go
  pkg/operator2/configobservation/console/observe_consoleurl_test.go
  pkg/operator2/configobservation/infrastructure/observe_apiserverurl.go
  pkg/operator2/configobservation/infrastructure/observe_apiserverurl_test.go
  pkg/operator2/configobservation/interfaces.go
  pkg/operator2/configobservation/routersecret/observe_router_secret.go
  pkg/operator2/configobservation/routersecret/observe_router_secret_test.go
  pkg/operator2/console.go
  pkg/operator2/infrastructure.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/starter.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#266 Fix upstream regression [1] where login box can be narrower than view…
  manifests/06_branding_secret.yaml
Labels: approved, lgtm

#270 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#267 Bug 1822648: Update product logos to new brand standard
  manifests/06_branding_secret.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#274 Bug 1825964: remove missing oauth-apiserver from image references
  manifests/image-references
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#275 [4.5] Bug 1825963: remove missing oauth-apiserver from image references
  manifests/image-references
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#269 Bug 1817748: Fix ingress state condition flapping
  pkg/controller/ingressstate/ingress_state_controller.go
  pkg/controller/ingressstate/ingress_state_controller_test.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/status.go
Labels: approved, bugzilla/valid-bug, lgtm

#279 Bug 1826341: ingress controller does not closes its connection to healthz
  pkg/controller/ingressstate/ingress_state_controller.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#280 [4.4] Bug 1826665: ingress controller does not closes its connection to healthz
  pkg/controller/ingressstate/ingress_state_controller.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm
