Repository openshift/cluster-authentication-operator, pull requests merged in 2020-07, with the labels that each got.

#296 Bug 1852312: fix template mounting to the oauth-server pods
  bindata/oauth-openshift/deployment.yaml
  pkg/operator2/assets/bindata.go
  test/e2e/templates_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#292 Refactor metadata to separate controller (part 1)
  pkg/controllers/metadata/metadata_controller.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/operator2/auth.go
  pkg/operator2/configmap.go
  pkg/operator2/ingress.go
  pkg/operator2/operator.go
  pkg/operator2/route.go
  pkg/operator2/route_test.go
  pkg/operator2/starter.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route_client.go
  vendor/modules.txt
Labels: approved, lgtm

#293 Refactor service-ca and payload config controller (part 2)
  bindata/oauth-openshift/oauth-service.yaml
  go.mod
  pkg/controllers/payload/payload_config_controller.go
  pkg/controllers/serviceca/service_ca_controller.go
  pkg/operator2/assets/bindata.go
  pkg/operator2/ca.go
  pkg/operator2/deployment.go
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
  pkg/operator2/secret.go
  pkg/operator2/secret_test.go
  pkg/operator2/service.go
  pkg/operator2/starter.go
Labels: approved, lgtm

#300 remove well-known readiness duplicated code + other cosmetic fixes
  pkg/controllers/metadata/metadata_controller.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/operator2/operator.go
Labels: approved, lgtm

#298 Bug 1853278: observe console-config config map without using a resource sync controller.
  pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
  pkg/controllers/configobservation/oauth/template_conversions.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#302 payload: handle panic when route is not ready
  pkg/controllers/payload/payload_config_controller.go
Labels: approved, lgtm

#301 controllers: abstract status setting logic
  pkg/controllers/common/conditions.go
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/ingressstate/ingress_state_controller.go
  pkg/controllers/metadata/metadata_controller.go
  pkg/controllers/payload/payload_config_controller.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/controllers/serviceca/service_ca_controller.go
  pkg/controllers/targetversion/target_version_controller.go
Labels: approved, lgtm

#306 Controller to check the different endpoints for authentication
  go.mod
  go.sum
  pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
  pkg/controllers/endpointaccessible/endpoint_accessible_controller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/modules.txt
Labels: approved, lgtm

#294 Use config observer from library-go
  pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
  pkg/controllers/configobservation/interfaces.go
  pkg/controllers/configobservation/oauth/observe_idps.go
  pkg/controllers/configobservation/oauth/observe_idps_test.go
  pkg/controllers/configobservation/oauth/observe_templates.go
  pkg/controllers/configobservation/oauth/observe_templates_test.go
  pkg/controllers/configobservation/oauth/observe_tokenconfig.go
  pkg/controllers/configobservation/oauth/observe_tokenconfig_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/oauth/observe_tokenconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#309 enables the encryption tests
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm

#310 wires the audit policy configuration
  bindata/oauth-apiserver/cm.yaml
  bindata/oauth-apiserver/deploy.yaml
  go.mod
  go.sum
  pkg/operator/assets/bindata.go
  pkg/operator/configobservation/config_observer_controller.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/test/library/encryption/errors.go
  vendor/modules.txt
Labels: approved, lgtm
