Repository openshift/cluster-authentication-operator, pull requests merged in 2020-09, with the labels that each got.

#332 Bug 1874713: deployment: don't panic when applying deployment fails
  pkg/controllers/deployment/deployment_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#334 bug 1875038: endpointaccessible: do not panic when no endpoints are found
  pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#336 Bug 1876471: Add ingress-operator as provider for router-certs
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#330 Bug 1866818: routercerts: always trust the default ingress ca
  pkg/controllers/routercerts/controller.go
  pkg/controllers/routercerts/controller_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#337 Bug 1876858: manifests: rename operator container to be more descriptive
  manifests/07_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#339 Bug 1877305: Fix proxy injection in operator
  manifests/07_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#338 Bug 1876874: [audit] log request and response bodies for identities
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#343 Bug 1878062: readiness controller: improve error messages
  pkg/controllers/readiness/wellknown_ready_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#341 Bug 1877803: don't error out on non-json output of password grant attempt
  pkg/controllers/configobservation/oauth/idp_conversions.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#344 Bug 1878776: ingressnodesavailable: add controller that checks if router can schedule pods
  pkg/controllers/ingressnodesavailable/OWNERS
  pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#346 Bug 1874056: bump library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/LICENSE
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/factory.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/generic.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/internalinterfaces/factory_interfaces.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/interface.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/interface.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/expansion_generated.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storageversionmigration.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#351 Bug 1880345: Provide more details for deployment pods
  go.mod
  go.sum
  pkg/controllers/common/deployment.go
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/targetversion/target_version_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/apps/deployment/status.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#324 Bug 1878648: oauth-apiserver: audit log oauthaccesstokens if fresh 4.6 install
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#352 bug 1871890: add current profile annotations to CVO manifests
  manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
  manifests/00_namespace.yaml
  manifests/02_config.cr.yaml
  manifests/02_service.yaml
  manifests/03_configmap.yaml
  manifests/03_openshift_service_ca.yaml
  manifests/03_operator_trusted_ca.yaml
  manifests/04_roles.yaml
  manifests/05_serviceaccount.yaml
  manifests/07_deployment.yaml
  manifests/08_clusteroperator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
