Repository openshift/cluster-authentication-operator, pull requests merged in 2020-01, with the labels that each got.

#231 Bug 1788135: Fix IPv6 Support
  manifests/03_configmap.yaml
  pkg/operator2/oauth.go
  pkg/operator2/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#236 fix bash syntax error in deployment
  bindata/oauth-openshift/deployment.yaml
  pkg/operator2/assets/bindata.go
Labels: approved, lgtm, size/XS

#235 Remove unused dockerfile and add gomod validation
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#239 fix trust-bundle destination
  bindata/oauth-openshift/deployment.yaml
  pkg/operator2/assets/bindata.go
Labels: approved, lgtm, size/XS

#240 redeploy on config changes
  pkg/operator2/deployment.go
Labels: approved, lgtm, size/XS

#237 Enable health checking of oauth-server endpoints
  manifests/03_openshift_service_ca.yaml
  manifests/07_deployment.yaml
  pkg/controller/ingressstate/ingress_state_controller.go
  pkg/controller/ingressstate/ingress_state_controller_test.go
  pkg/operator2/service.go
  pkg/operator2/starter.go
Labels: approved, lgtm, size/XL

#241 Add oauth-apiserver to manifest/image-references
  manifests/image-references
Labels: approved, lgtm, size/XS

#244 Update login templates to PatternFly 4 design
  manifests/06_branding_secret.yaml
Labels: approved, lgtm, size/XS

#246 Pick up mobile fix
  manifests/06_branding_secret.yaml
Labels: approved, lgtm, size/XS
