Repository openshift/cluster-authentication-operator, pull requests merged in 2020-05, with the labels that each got.

#276 Bug 1834852: Add make target to run operator with telepresence
  .gitignore
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#284 Bug 1834852: Fix bad vendoring from telepresence PR
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#257 Bug 1824167: The oauth server should wait until it is out of rotation to shut down
  pkg/operator2/deployment.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#273 Bug 1824800: explicitly set oauth-server container's root file system to writable
  bindata/oauth-openshift/deployment.yaml
  manifests/07_deployment.yaml
  pkg/operator2/assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#248 Bug 1727983: OIDC IdPs: allow challenge flows if OIDC server advertises password grants
  go.mod
  go.sum
  pkg/operator2/idp.go
  pkg/operator2/oauth.go
  test/e2e/certs_test.go
  test/e2e/operator_test.go
  test/e2e/password_grant_check_test.go
  test/library/certs.go
  test/library/client.go
  test/library/gitlabidp.go
  test/library/idpdeployment.go
  test/library/operand.go
  test/library/waits.go
  vendor/gopkg.in/square/go-jose.v2/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/README.md
  vendor/gopkg.in/square/go-jose.v2/json/decode.go
  vendor/gopkg.in/square/go-jose.v2/json/encode.go
  vendor/gopkg.in/square/go-jose.v2/json/indent.go
  vendor/gopkg.in/square/go-jose.v2/json/scanner.go
  vendor/gopkg.in/square/go-jose.v2/json/stream.go
  vendor/gopkg.in/square/go-jose.v2/json/tags.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M
