Repository openshift/cluster-authentication-operator, pull requests merged in 2020-08, with the labels that each got.

#313 Bug 1861789: improve password-grant discovery message on non-JSON server response
  pkg/controllers/configobservation/oauth/idp_conversions.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#312 Bug 1777137: don't post new observed config on resources validation
  go.mod
  go.sum
  pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
  pkg/controllers/configobservation/oauth/observe_idps.go
  pkg/operator/configobservation/config_observer_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#314 Bug 1859591: version controller: honor system CA bundle when checking route health
  pkg/controllers/targetversion/target_version_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#318 Bug 1841372: prevent Available=true until all kube-apiservers have restarted
  pkg/controllers/readiness/unsupported_override.go
  pkg/controllers/readiness/wellknown_ready_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#321 logs when the encryption deployer hasn't yet converged
  pkg/operator/apiservices/sync_take_over_apiservices_oauth_apiserver.go
Labels: approved, lgtm

#322 Bug 1867908: add connection timeouts and proxy from env to http client
  pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#323 authentication operator is marked available because the deployment is missing
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
  pkg/controllers/endpointaccessible/endpoint_accessible_controller_test.go
  pkg/controllers/endpointaccessible/endpoints_accessible.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/controllers/targetversion/target_version_controller.go
  pkg/operator/starter.go
Labels: approved, lgtm

#297 [4.3] Bug 1842465: explicitly set operator's and operand's container's root file system to writable
  manifests/07_deployment.yaml
  pkg/operator2/deployment.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#328 Bug 1870565: deployment: avoid degraded due to conflict error
  pkg/controllers/deployment/deployment_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
