Repository openshift/cluster-authentication-operator, pull requests merged in 2021-04, with the labels that each got.

#429 extends shutdown delay duration to 10 seconds
  bindata/oauth-apiserver/deploy.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Labels: approved, lgtm

#432 e2e: fix the token names in tokentimeout test to match the new format
  test/e2e-encryption-perf/encryption_perf_test.go
  test/e2e/tokentimeout_test.go
  test/library/client.go
  test/library/encryption/helpers.go
Labels: approved, lgtm

#433 Bug 1946540: only configure webhook authenticators when oauth-apiservers are ready during upgrade
  pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#431 Add management workload annotations
  bindata/oauth-apiserver/deploy.yaml
  bindata/oauth-apiserver/ns.yaml
  bindata/oauth-openshift/deployment.yaml
  bindata/oauth-openshift/ns.yaml
  manifests/00_namespace.yaml
  manifests/07_deployment.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#435 Bug 1946540: fix configuring webhook authenticators on upgrade
  pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#437 [4.7] Bug 1949941: add a scraper and an alert to check for old-style tokens
  go.sum
  manifests/0000_90_cluster-authentication-operator_03_prometheusrule.yaml
  pkg/controllers/oldtokensscraper/old_tokens_scraper.go
  pkg/controllers/oldtokensscraper/old_tokens_scraper_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/interface.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/interface.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/oauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/oauthauthorizetoken.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/oauthclient.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/oauthclientauthorization.go
  vendor/github.com/openshift/client-go/oauth/informers/externalversions/oauth/v1/useroauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/oauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/oauthauthorizetoken.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/oauthclient.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/oauthclientauthorization.go
  vendor/github.com/openshift/client-go/oauth/listers/oauth/v1/useroauthaccesstoken.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#434 Rename workload annotations
  bindata/oauth-apiserver/deploy.yaml
  bindata/oauth-openshift/deployment.yaml
  manifests/07_deployment.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#441 Bug 1954544: endpoints controller: actually use the context-constrained request
  pkg/controllers/proxyconfig/proxyconfig_controller.go
  pkg/libs/endpointaccessible/endpoint_accessible_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
