Repository openshift/cluster-authentication-operator, pull requests merged in 2021-11, with the labels that each got.

#496 Exclude operator config for ibm-cloud-managed profile
  manifests/02_config.cr.yaml
Labels: approved, lgtm

#502 typo fix: enpoints -> endpoints
  pkg/libs/endpointaccessible/endpoint_accessible_controller.go
Labels: approved, lgtm

#503 Bug 2019832: pkg/operator: configure high inertia for apiserver and OAuthServer
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#504 pkg/operator: set high inertia for all topologies except SingleReplica
  pkg/operator/starter.go
Labels: approved, lgtm

#473 Bug 1996647: endpointsaccessible: clarify degraded message when DNS is broken
  pkg/libs/endpointaccessible/endpoint_accessible_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#508 test/lib: Set `PROXY_ADDRESS_FORWARDING` for keycloak
  test/library/keycloakidp.go
Labels: approved, lgtm

#512 test/library: Pin keycloak contianer label to 15.0.1
  test/library/keycloakidp.go
Labels: approved, lgtm

#506 Bug 1982726: encryption-controller: sync secrets conditionally
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apigroup.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/etcd/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/encryption/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/unionrevisionedpod.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/secrets/secrets.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/statemachine/transition.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
