Repository openshift/cluster-authentication-operator, pull requests merged in 2021-09, with the labels that each got.

#476 bug 1998031: Deploy PDB to prevent more than one replica going unavailable
  bindata/oauth-apiserver/oauth-apiserver-pdb.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#480 Update Go version in the images
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm

#488 [4.8] bug 2003946: Deploy PDB to prevent more than one replica going unavailable
  bindata/oauth-apiserver/oauth-apiserver-pdb.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#492 podsecurity: enforce privileged for openshift-oauth-apiserver namespace
  bindata/oauth-apiserver/ns.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm
