Repository openshift/cluster-authentication-operator, pull requests merged in 2021-01, with the labels that each got.

#394 Bug 1901774: manifests: add liveness probe to the operator's deployment
  manifests/07_deployment.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#395 Bug 1905329: oauth-apiserver deployment: add cpu and memory requests
  bindata/oauth-apiserver/deploy.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#399 Bug 1916949: manifests: exclude rbac resources in openshift-oauth-apiserver namespace from hosted profile
  manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#400 Bug 1917114: proxyconfig controller: match URL to noproxy correctly
  pkg/controllers/proxyconfig/proxyconfig_controller.go
  pkg/controllers/proxyconfig/proxyconfig_controller_test.go
  pkg/controllers/proxyconfig/proxymatching.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#402 Bug 1921275: deploymentController: treat error retrieving authentication.operator/cluster
  pkg/controllers/deployment/deployment_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
