Repository openshift/cluster-authentication-operator, pull requests merged in 2021-06, with the labels that each got.

#449 Bug 1967398: operator: add OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded to stale conditions
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#450 Bug 1965929: bump lib-go to get improved performance for the CSR approver
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
  vendor/github.com/openshift/library-go/pkg/operator/csr/csr_approver.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#451 Bug 1879182: oauth-apiserver: audit policies now use 'secure-' by default
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#453 Bug 1969631: encryption controllers wait for all informers before running the sync loops
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#448 readme: update references to developer guide
  README.md
Labels: approved, lgtm

#418 [4.7] Bug 1971087: add a controller to remove webhooktokenauthenticator config
  pkg/controllers/webhooksremover/webhooksremover.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#457 bump library-go to get context fixes
  go.mod
  go.sum
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/metadata/metadata_controller.go
  pkg/controllers/payload/payload_config_controller.go
  pkg/controllers/routercerts/controller.go
  pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/legacy.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apigroup.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/credentialsrequest.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
Labels: approved, lgtm

#458 Bug 1977054: observe api-audiences for the oauth-apiserver
  pkg/operator/configobservation/authentication/apiaudiences.go
  pkg/operator/configobservation/authentication/apiaudiences_test.go
  pkg/operator/configobservation/configobservercontroller/config_observer_controller.go
  pkg/operator/configobservation/listers.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
  test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
