Repository openshift/cluster-authentication-operator, pull requests merged in 2021-07, with the labels that each got.

#460 add dynamic audit policy controller
  bindata/oauth-apiserver/deploy.yaml
  go.mod
  go.sum
  pkg/operator/assets/bindata.go
  pkg/operator/configobservation/configobservercontroller/config_observer_controller.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/csr/csr_approver.go
  vendor/modules.txt
Labels: approved, lgtm

#430 Custom Certs for OAuth Route
  bindata/oauth-openshift/route.yaml
  pkg/controllers/common/ingress_config.go
  pkg/controllers/common/ingress_config_test.go
  pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
  pkg/controllers/configobservation/interfaces.go
  pkg/controllers/configobservation/routersecret/observe_router_secret.go
  pkg/controllers/configobservation/routersecret/observe_router_secret_test.go
  pkg/controllers/customroute/custom_route_conditions.go
  pkg/controllers/customroute/custom_route_controller.go
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/metadata/metadata_controller.go
  pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
  pkg/controllers/oauthendpoints/oauth_endpoints_controller.go
  pkg/controllers/routercerts/controller.go
  pkg/controllers/routercerts/controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/datasync/validation.go
  pkg/operator/starter.go
  test/e2e/custom_route_test.go
Labels: approved, lgtm

#466 encryption condition controller doesn't reset previously set condition
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#461 Bug 1977027: Remove not needed Prometheus Rule
  manifests/0000_90_cluster-authentication-operator_03_prometheusrule.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#464 distribute oauth-server trust via a openshift-config-managed configmap
  bindata/oauth-openshift/trust_distribution_role.yaml
  bindata/oauth-openshift/trust_distribution_rolebinding.yaml
  pkg/controllers/trustdistribution/trustdistribution_controller.go
  pkg/operator/assets/bindata.go
  pkg/operator/starter.go
  test/e2e/custom_route_test.go
Labels: approved, lgtm

#468 Bug 1978193: csr request: use generate names to prevent getting stuck waiting for a cert
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#469 Bug 1986829: metrics: use client cert auth for metrics scraping
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#467 Bug 1979303: clear encryption conditions when there is no work to be done
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apigroup.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
