Repository openshift/cluster-authentication-operator, pull requests merged in 2021-05, with the labels that each got.

#440 [4.7] Bug 1941840: endpoints controller: close response bodies
  pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
  pkg/controllers/proxyconfig/proxyconfig_controller.go
  pkg/controllers/proxyconfig/proxyconfig_controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#442 Bug 1939580: wellknownready: delay going degraded on oauthmetadata changes
  pkg/controllers/common/conditions.go
  pkg/controllers/common/conditions_test.go
  pkg/controllers/readiness/wellknown_ready_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#428 Bug 1955749: OCP oauth translations for login pages
  bindata/oauth-openshift/branding-secret.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#444 Bug 1953041: manifests/deployment: bump cpu and memory resource requests
  manifests/07_deployment.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#439 Bug 1953563: Add .ci-operator.yaml with build_root_image
  .ci-operator.yaml
  Dockerfile.rhel7
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#438 Bug 1950379: routersecret: sync only the cert/key pair for the default domain
  go.mod
  go.sum
  pkg/controllers/common/config.go
  pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
  pkg/controllers/routercerts/controller.go
  pkg/controllers/routercerts/controller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#446 Bug 1943804: stub for splitting encryption tests
  Makefile
  test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#447 Bug 1943804: splits the encryption tests
  test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
  test/e2e-encryption/encryption_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
