Repository openshift/cluster-authentication-operator, pull requests merged in 2022-01, with the labels that each got.

#528 Bug 2030961: endpoints checker: check only the custom hostname if configured
  pkg/controllers/oauthendpoints/oauth_endpoints_controller.go
  pkg/controllers/oauthendpoints/oauth_endpoints_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#525 Bug 2034484: fix:library-go nil pointer issue
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#514 bug 2039670: Create the PDB dynamically so it does not get created on the SNO topology
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#526 golang 1.16 bump: Updating ose-cluster-authentication-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#534 Bug 2024841: use latest keycloak for testing
  test/library/keycloakidp.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#537 bug 2042038: bump library go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#538 bug 2039670: Sync the library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#533 bug 2040521: routeName used as customSecretName
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#542 Bug 2039417: remove degraded condition 4.9
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
