Repository openshift/cluster-authentication-operator, pull requests merged in 2022-07, with the labels that each got.

#573 Bug 2078287: only ever include certificates in the oauth-serving-cert CM
  pkg/controllers/trustdistribution/trustdistribution_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#571 Updating ose-cluster-authentication-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm

#574 [4.11] Bug 2107028: only ever include certificates in the oauth-serving-cert CM
  pkg/controllers/trustdistribution/trustdistribution_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, staff-eng-approved, backport-risk-assessed

#577 [4.10] Bug 2084054: only ever include certificates in the oauth-serving-cert CM
  pkg/controllers/trustdistribution/trustdistribution_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#578 [4.9] Bug 2107027: only ever include certificates in the oauth-serving-cert CM
  pkg/controllers/trustdistribution/trustdistribution_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed
