Repository openshift/cluster-authentication-operator, pull requests merged in 2024-10, with the labels that each got.

#709 OCPBUGS-42745: manifests should not use APIs that are removed in upcoming releases
  manifests/09_flowschema.yaml
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#705 API-1835: Migrate WellKnownReadyController to SSA
  pkg/controllers/common/conditions.go
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/operator/starter.go
Labels: approved, lgtm, jira/valid-reference

#710 API-1835: demonstration mutation recording client
  cmd/authentication-operator/main.go
  go.mod
  go.sum
  pkg/cmd/mom/apply_configuration_command.go
  pkg/operator/replacement_starter.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/encoding.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/get.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/io.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_writer.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/read_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/readwrite_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/serialized_request.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/base-policy.yaml
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/test_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/github.com/openshift/multi-operator-manager/LICENSE
  vendor/github.com/openshift/multi-operator-manager/pkg/flagtypes/time.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/README.md
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/apply_configuration.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/client_mutations.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/command.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_apply_configuration.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_mutations.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/equivalence.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/options.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/write.go
  vendor/k8s.io/cli-runtime/LICENSE
  vendor/k8s.io/cli-runtime/pkg/genericiooptions/io_options.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#715 API-1835: Bump library-go to get WorkloadController SSA
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/README.md
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/aggregated-discovery-api.yaml
  vendor/github.com/openshift/library-go/pkg/manifestclient/default-discovery/aggregated-discovery-apis.yaml
  vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/read_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#722 NO-JIRA: add relatedResources to authentication for collection if operator crashes
  manifests/08_clusteroperator.yaml
Labels: approved, lgtm, jira/valid-reference

#720 API-1835: adds `output-resources` to cluster-authentication operator.
  cmd/authentication-operator/main.go
  go.mod
  go.sum
  pkg/cmd/mom/apply_configuration_command.go
  pkg/cmd/mom/output_resources_command.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/serialized_request.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/options.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/command.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/options.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/types.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#727 OCPBUGS-42932: ensure annotations map exists before mutating it
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/manifestclient/context.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#721 API-1835: Bump library-go to get SSA in multiple controllers
  go.mod
  go.sum
  pkg/operator/replacement_starter.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/readwrite_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/managementstatecontroller/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#725 API-1835: Use test-operator-integration target from build-machinery-go
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/mom.mk
  vendor/github.com/openshift/build-machinery-go/scripts/test-operator-integration.sh
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#728 API-1835: name all the runone functions
  go.mod
  go.sum
  pkg/cmd/mom/apply_configuration_command.go
  pkg/cmd/mom/output_resources_command.go
  pkg/operator/replacement_starter.go
  pkg/operator/starter.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/apply_configuration.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/client_mutations.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/command.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_apply_configuration.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_mutations.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/equivalence.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/options.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/easy_creation.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/types.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#730 API-1835: Add input-resources
  cmd/authentication-operator/main.go
  go.mod
  go.sum
  pkg/cmd/mom/input_resources_command.go
  vendor/github.com/PaesslerAG/gval/.gitignore
  vendor/github.com/PaesslerAG/gval/.travis.yml
  vendor/github.com/PaesslerAG/gval/LICENSE
  vendor/github.com/PaesslerAG/gval/README.md
  vendor/github.com/PaesslerAG/gval/evaluable.go
  vendor/github.com/PaesslerAG/gval/functions.go
  vendor/github.com/PaesslerAG/gval/gval.go
  vendor/github.com/PaesslerAG/gval/language.go
  vendor/github.com/PaesslerAG/gval/operator.go
  vendor/github.com/PaesslerAG/gval/parse.go
  vendor/github.com/PaesslerAG/gval/parser.go
  vendor/github.com/PaesslerAG/gval/prtg-batmin-gopher.png
  vendor/github.com/PaesslerAG/jsonpath/.gitignore
  vendor/github.com/PaesslerAG/jsonpath/.travis.yml
  vendor/github.com/PaesslerAG/jsonpath/LICENSE
  vendor/github.com/PaesslerAG/jsonpath/README.md
  vendor/github.com/PaesslerAG/jsonpath/jsonpath.go
  vendor/github.com/PaesslerAG/jsonpath/parse.go
  vendor/github.com/PaesslerAG/jsonpath/path.go
  vendor/github.com/PaesslerAG/jsonpath/placeholder.go
  vendor/github.com/PaesslerAG/jsonpath/selector.go
  vendor/github.com/PaesslerAG/jsonpath/test.sh
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/command.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/easy_creation.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/options.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/prune_mustgather.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/resource.go
  vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryinputresources/types.go
  vendor/github.com/shopspring/decimal/.gitignore
  vendor/github.com/shopspring/decimal/.travis.yml
  vendor/github.com/shopspring/decimal/CHANGELOG.md
  vendor/github.com/shopspring/decimal/LICENSE
  vendor/github.com/shopspring/decimal/README.md
  vendor/github.com/shopspring/decimal/decimal-go.go
  vendor/github.com/shopspring/decimal/decimal.go
  vendor/github.com/shopspring/decimal/rounding.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#731 API-1835: use manifestclient.RecommendedRESTConfig()
  pkg/operator/replacement_starter.go
Labels: approved, lgtm, jira/valid-reference
