Repository openshift/cluster-authentication-operator, pull requests merged in 2024-04, with the labels that each got.

#664 OCPBUGS-32089: wellknown-readiness: perform several attempts to connect before going unavailable
  pkg/controllers/readiness/wellknown_ready_controller.go
  pkg/controllers/readiness/wellknown_ready_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#666 NO-JIRA: e2e Keycloak: retry logging in as admin
  test/library/keycloakidp.go
Labels: approved, lgtm, jira/valid-reference

#640 OCPBUGS-22969: Use v1 for flowcontrol API
  manifests/09_flowschema.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#656 AUTH-482: set required-scc for openshift workloads
  Makefile
  bindata/assets.go
  bindata/oauth-apiserver/deploy.yaml
  bindata/oauth-openshift/deployment.yaml
  go.mod
  go.sum
  manifests/07_deployment.yaml
  pkg/controllers/customroute/custom_route_controller.go
  pkg/controllers/deployment/default_deployment.go
  pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
  pkg/dependencymagnet/dependencymagnet.go
  pkg/operator/assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/workload/sync_openshift_oauth_apiserver.go
  pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
  pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
