Repository openshift/cluster-authentication-operator, pull requests merged in 2025-02, with the labels that each got.

#752 MON-4129: adjust Prometheus classic histograms 'le' related selectors in relabel config to accommodate the update to Prometheus v3
  manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#756 NO-JIRA: OWNERS: update approvers
  OWNERS
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#751 OCPBUGS-43610,CONSOLE-4434: update login templates to use PF6 and add validation
  bindata/oauth-openshift/branding-secret.yaml
  test-data/apply-configuration/overall/minimal-cluster/expected-output/Management/Create/namespaces/openshift-authentication/core/secrets/dc0d-body-v4-0-config-system-ocp-branding-template.yaml
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#713 AUTH-541: OIDC structured auth config
  pkg/controllers/externaloidc/externaloidc_controller.go
  pkg/controllers/externaloidc/externaloidc_controller_test.go
  pkg/operator/replacement_starter.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-reference

#760 OCPBUGS-51981: fix: update starter path to account for mom integration
  pkg/operator/replacement_starter.go
  pkg/operator/starter.go
  test-data/apply-configuration/overall/minimal-cluster/expected-output/controller-results.yaml
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
