Repository openshift/cluster-authentication-operator, pull requests merged in 2025-03, with the labels that each got.

#714 NO-JIRA: Keycloak e2e test improvements
  test/library/keycloakidp.go
Labels: approved, lifecycle/stale, lgtm, jira/valid-reference

#761 OCPEDGE-1510: feat: add minimum count for DualReplica
  pkg/controllers/readiness/unsupported_override.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#757 OCPBUGS-48176: Avoid duplicate OAuth client creation
  pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
  pkg/controllers/oauthclientscontroller/oauthclientscontroller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only
